/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate user and return JWT tokens.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Refresh access token using refresh token.
         */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current authenticated user info.
         */
        get: operations["get_current_user_info_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description Register new user (for demo - in production add hotel verification).
         */
        post: operations["register_user_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Leads
         * @description List leads with filtering and pagination.
         */
        get: operations["list_leads_api_v1_leads_get"];
        put?: never;
        /**
         * Create Lead
         * @description Create new lead with automatic deduplication check.
         */
        post: operations["create_lead_api_v1_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lead
         * @description Get lead by ID.
         */
        get: operations["get_lead_api_v1_leads__lead_id__get"];
        /**
         * Update Lead
         * @description Update lead.
         */
        put: operations["update_lead_api_v1_leads__lead_id__put"];
        post?: never;
        /**
         * Delete Lead
         * @description Delete lead.
         */
        delete: operations["delete_lead_api_v1_leads__lead_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/segment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Lead Segment
         * @description Update lead segment manually.
         */
        put: operations["update_lead_segment_api_v1_leads__lead_id__segment_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score Lead
         * @description Score individual lead.
         */
        post: operations["score_lead_api_v1_leads__lead_id__score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/score/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Score Leads
         * @description Score multiple leads in batch (async operation).
         */
        post: operations["bulk_score_leads_api_v1_leads_score_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leads Summary
         * @description Get lead statistics summary.
         */
        get: operations["get_leads_summary_api_v1_leads_stats_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Campaigns
         * @description List campaigns with filtering and pagination.
         */
        get: operations["list_campaigns_api_v1_campaigns_get"];
        put?: never;
        /**
         * Create Campaign
         * @description Create new campaign.
         */
        post: operations["create_campaign_api_v1_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Campaign
         * @description Get campaign by ID.
         */
        get: operations["get_campaign_api_v1_campaigns__campaign_id__get"];
        /**
         * Update Campaign
         * @description Update campaign.
         */
        put: operations["update_campaign_api_v1_campaigns__campaign_id__put"];
        post?: never;
        /**
         * Delete Campaign
         * @description Delete campaign.
         */
        delete: operations["delete_campaign_api_v1_campaigns__campaign_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Campaign
         * @description Activate campaign.
         */
        post: operations["activate_campaign_api_v1_campaigns__campaign_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Campaign
         * @description Pause campaign.
         */
        post: operations["pause_campaign_api_v1_campaigns__campaign_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Campaign
         * @description Execute campaign (queue messages for sending).
         */
        post: operations["execute_campaign_api_v1_campaigns__campaign_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Campaign Stats
         * @description Get campaign statistics.
         */
        get: operations["get_campaign_stats_api_v1_campaigns__campaign_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Campaign Target Leads
         * @description Get leads matching campaign targeting criteria.
         */
        get: operations["get_campaign_target_leads_api_v1_campaigns__campaign_id__leads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description List message templates.
         */
        get: operations["list_templates_api_v1_templates_get"];
        put?: never;
        /**
         * Create Template
         * @description Create message template.
         */
        post: operations["create_template_api_v1_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Template
         * @description Get message template.
         */
        get: operations["get_template_api_v1_templates__template_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CampaignCreate
         * @description Schema for creating campaign.
         */
        CampaignCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            campaign_type: components["schemas"]["CampaignType"];
            trigger_event?: components["schemas"]["TriggerEvent"] | null;
            /** Trigger Delay Minutes */
            trigger_delay_minutes?: number | null;
            /** Schedule Cron */
            schedule_cron?: string | null;
            /** Schedule Timezone */
            schedule_timezone?: string | null;
            /** Target Segments */
            target_segments?: string[];
            /** Target Filters */
            target_filters?: Record<string, never> | null;
            /** Channels */
            channels: components["schemas"]["MessageChannel"][];
            /** Sms Template Id */
            sms_template_id?: string | null;
            /** Email Template Id */
            email_template_id?: string | null;
            /**
             * Enable Ab Test
             * @default false
             */
            enable_ab_test: boolean;
            /** Ab Test Split */
            ab_test_split?: number | null;
            /** Ab Variant Template Id */
            ab_variant_template_id?: string | null;
            /** Throttle Per Minute */
            throttle_per_minute?: number | null;
            /** Max Sends Per Lead */
            max_sends_per_lead?: number | null;
        };
        /**
         * CampaignListResponse
         * @description Schema for paginated campaign list.
         */
        CampaignListResponse: {
            /** Items */
            items: components["schemas"]["CampaignResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
        };
        /**
         * CampaignResponse
         * @description Schema for campaign response.
         */
        CampaignResponse: {
            /**
             * Id
             * Format: uuid4
             */
            id: string;
            /**
             * Hotel Id
             * Format: uuid4
             */
            hotel_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            campaign_type: components["schemas"]["CampaignType"];
            status: components["schemas"]["CampaignStatus"];
            trigger_event: components["schemas"]["TriggerEvent"] | null;
            /** Trigger Delay Minutes */
            trigger_delay_minutes: number | null;
            /** Schedule Cron */
            schedule_cron: string | null;
            /** Schedule Timezone */
            schedule_timezone: string | null;
            /** Target Segments */
            target_segments: string[];
            /** Target Filters */
            target_filters: Record<string, never> | null;
            /** Channels */
            channels: components["schemas"]["MessageChannel"][];
            /** Sms Template Id */
            sms_template_id: string | null;
            /** Email Template Id */
            email_template_id: string | null;
            /** Enable Ab Test */
            enable_ab_test: boolean;
            /** Ab Test Split */
            ab_test_split: number | null;
            /** Ab Variant Template Id */
            ab_variant_template_id: string | null;
            /** Throttle Per Minute */
            throttle_per_minute: number | null;
            /** Max Sends Per Lead */
            max_sends_per_lead: number | null;
            /** Total Sent */
            total_sent: number;
            /** Total Delivered */
            total_delivered: number;
            /** Total Failed */
            total_failed: number;
            /** Total Opened */
            total_opened: number;
            /** Total Clicked */
            total_clicked: number;
            /** Total Cost */
            total_cost: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CampaignStatsResponse
         * @description Schema for campaign statistics.
         */
        CampaignStatsResponse: {
            /**
             * Campaign Id
             * Format: uuid4
             */
            campaign_id: string;
            /** Total Sent */
            total_sent: number;
            /** Total Delivered */
            total_delivered: number;
            /** Total Failed */
            total_failed: number;
            /** Total Opened */
            total_opened: number;
            /** Total Clicked */
            total_clicked: number;
            /** Delivery Rate */
            delivery_rate: number;
            /** Open Rate */
            open_rate: number;
            /** Click Rate */
            click_rate: number;
            /** Total Cost */
            total_cost: number;
            /** Avg Cost Per Send */
            avg_cost_per_send: number;
            /** By Channel */
            by_channel: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Ab Test Results */
            ab_test_results?: Record<string, never> | null;
        };
        /**
         * CampaignStatus
         * @description Campaign status
         * @enum {string}
         */
        CampaignStatus: "draft" | "active" | "paused" | "completed";
        /**
         * CampaignType
         * @description Campaign types
         * @enum {string}
         */
        CampaignType: "trigger" | "scheduled" | "manual";
        /**
         * CampaignUpdate
         * @description Schema for updating campaign.
         */
        CampaignUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            status?: components["schemas"]["CampaignStatus"] | null;
            /** Trigger Delay Minutes */
            trigger_delay_minutes?: number | null;
            /** Schedule Cron */
            schedule_cron?: string | null;
            /** Target Segments */
            target_segments?: string[] | null;
            /** Target Filters */
            target_filters?: Record<string, never> | null;
            /** Channels */
            channels?: components["schemas"]["MessageChannel"][] | null;
            /** Sms Template Id */
            sms_template_id?: string | null;
            /** Email Template Id */
            email_template_id?: string | null;
            /** Enable Ab Test */
            enable_ab_test?: boolean | null;
            /** Throttle Per Minute */
            throttle_per_minute?: number | null;
        };
        /**
         * ConsentStatus
         * @description Consent status
         * @enum {string}
         */
        ConsentStatus: "opted_in" | "opted_out" | "pending";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LeadCreate
         * @description Schema for creating a new lead.
         */
        LeadCreate: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Phone
             * @description E.164 format: +251911234567
             */
            phone: string;
            /** Email */
            email?: string | null;
            /**
             * Country
             * @description ISO 3166-1 alpha-2
             */
            country: string;
            /**
             * Language
             * @default en
             */
            language: string;
            source: components["schemas"]["LeadSource"];
            /** Source Details */
            source_details?: string | null;
            /** @default pending */
            consent_status: components["schemas"]["ConsentStatus"];
        };
        /**
         * LeadListResponse
         * @description Schema for paginated lead list.
         */
        LeadListResponse: {
            /** Items */
            items: components["schemas"]["LeadResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
        };
        /**
         * LeadResponse
         * @description Schema for lead response.
         */
        LeadResponse: {
            /**
             * Id
             * Format: uuid4
             */
            id: string;
            /**
             * Hotel Id
             * Format: uuid4
             */
            hotel_id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Phone */
            phone: string;
            /** Email */
            email?: string | null;
            /** Country */
            country: string;
            /** Language */
            language: string;
            source: components["schemas"]["LeadSource"];
            /** Source Details */
            source_details?: string | null;
            segment?: components["schemas"]["LeadSegment"] | null;
            /** Conversion Score */
            conversion_score?: number | null;
            /** Conversion Probability */
            conversion_probability?: number | null;
            /** Quality Score */
            quality_score?: number | null;
            /** Last Scored At */
            last_scored_at?: string | null;
            /**
             * Total Bookings
             * @default 0
             */
            total_bookings: number;
            /**
             * Total Revenue
             * @default 0
             */
            total_revenue: number;
            /** Last Booking Date */
            last_booking_date?: string | null;
            /** Last Contact Date */
            last_contact_date?: string | null;
            consent_status: components["schemas"]["ConsentStatus"];
            /**
             * Is Duplicate
             * @default false
             */
            is_duplicate: boolean;
            /** Extra Data */
            extra_data?: Record<string, never> | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * LeadScoreResponse
         * @description Schema for lead scoring result.
         */
        LeadScoreResponse: {
            /**
             * Lead Id
             * Format: uuid4
             */
            lead_id: string;
            /** Conversion Score */
            conversion_score: number;
            /** Conversion Probability */
            conversion_probability: number;
            /** Quality Score */
            quality_score: number;
            segment: components["schemas"]["LeadSegment"];
            /**
             * Scored At
             * Format: date-time
             */
            scored_at: string;
            /** Factors */
            factors: Record<string, never>;
        };
        /**
         * LeadSegment
         * @description Lead segments
         * @enum {string}
         */
        LeadSegment: "hot" | "warm" | "cold" | "unqualified";
        /**
         * LeadSegmentUpdate
         * @description Schema for updating lead segment.
         */
        LeadSegmentUpdate: {
            segment: components["schemas"]["LeadSegment"];
            /** Reason */
            reason?: string | null;
        };
        /**
         * LeadSource
         * @description Lead source types
         * @enum {string}
         */
        LeadSource: "pms" | "csv" | "meta_ads" | "data_broker" | "manual";
        /**
         * LeadUpdate
         * @description Schema for updating a lead.
         */
        LeadUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Country */
            country?: string | null;
            /** Language */
            language?: string | null;
            consent_status?: components["schemas"]["ConsentStatus"] | null;
            /** Extra Data */
            extra_data?: Record<string, never> | null;
        };
        /**
         * MessageChannel
         * @description Message channels
         * @enum {string}
         */
        MessageChannel: "sms" | "email";
        /**
         * MessageTemplateCreate
         * @description Schema for creating message template.
         */
        MessageTemplateCreate: {
            /** Name */
            name: string;
            channel: components["schemas"]["MessageChannel"];
            /** Subject */
            subject?: string | null;
            /** Body */
            body: string;
            /** Variables */
            variables?: string[];
            /**
             * Language
             * @default en
             */
            language: string;
        };
        /**
         * MessageTemplateResponse
         * @description Schema for message template response.
         */
        MessageTemplateResponse: {
            /**
             * Id
             * Format: uuid4
             */
            id: string;
            /**
             * Hotel Id
             * Format: uuid4
             */
            hotel_id: string;
            /** Name */
            name: string;
            channel: components["schemas"]["MessageChannel"];
            /** Subject */
            subject: string | null;
            /** Body */
            body: string;
            /** Variables */
            variables: string[];
            /** Language */
            language: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Role
         * @description User roles for RBAC
         * @enum {string}
         */
        Role: "owner" | "manager" | "staff" | "api";
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TriggerEvent
         * @description Trigger events
         * @enum {string}
         */
        TriggerEvent: "lead.created" | "checkout.completed" | "booking.confirmed" | "checkin" | "checkout";
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /** Hotel Id */
            hotel_id: string;
            /** @default staff */
            role: components["schemas"]["Role"];
        };
        /** UserLogin */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid4
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["Role"];
            /**
             * Hotel Id
             * Format: uuid4
             */
            hotel_id: string;
            /** Is Active */
            is_active: boolean;
            /** Is Verified */
            is_verified: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query: {
                refresh_token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    register_user_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_leads_api_v1_leads_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                segment?: components["schemas"]["LeadSegment"] | null;
                source?: string | null;
                country?: string | null;
                consent_status?: string | null;
                min_conversion_score?: number | null;
                max_conversion_score?: number | null;
                is_duplicate?: boolean | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lead_api_v1_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_api_v1_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lead_api_v1_leads__lead_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_lead_api_v1_leads__lead_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lead_segment_api_v1_leads__lead_id__segment_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadSegmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_lead_api_v1_leads__lead_id__score_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_score_leads_api_v1_leads_score_bulk_post: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leads_summary_api_v1_leads_stats_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_campaigns_api_v1_campaigns_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status?: components["schemas"]["CampaignStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_campaign_api_v1_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_campaign_api_v1_campaigns__campaign_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_campaign_api_v1_campaigns__campaign_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_campaign_api_v1_campaigns__campaign_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_campaign_api_v1_campaigns__campaign_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_campaign_api_v1_campaigns__campaign_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_campaign_api_v1_campaigns__campaign_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string[] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_campaign_stats_api_v1_campaigns__campaign_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_campaign_target_leads_api_v1_campaigns__campaign_id__leads_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_templates_get: {
        parameters: {
            query?: {
                channel?: components["schemas"]["MessageChannel"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageTemplateResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_api_v1_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageTemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageTemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_api_v1_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageTemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
